### ISSUE TITLE
locale to save

### ISSUE THREAD

**Issue by fabi0w** [BorisChumichev/node-nthline#1]
After locating, how do I editing the line and save it?
ps.  in locate.. show me:

```
const nthline = require('nthline')
, filePath = path.join(__dirname, '/logs/rooms/2017/05/12/p_2')
, rowNumber = data.line
console.log(filePath) // C:\Apache24\htdocs\select2-bootstrap\logs\rooms\2017\05\12\p_2
nthline(rowNumber, filePath)
	.then(line => console.log(line))
```

   throw er; // Unhandled 'error' event   
Error: EISDIR: illegal operation on a directory, read
    at Error (native)

**Comment by BorisChumichev** [comment]
nthline expects a path to a target file you want to read from as a second argument. EISDIR — error means that you provided a directory instead.

**Comment by fabi0w** [comment]
okay... now change to file and not showed nothing... my console only showed the file directory and not the content file line [http://i.imgur.com/agfYqKW.png](http://i.imgur.com/agfYqKW.png)
```
const nthline = require('nthline')
 , filePath = path.join(__dirname, log_dir)
, rowNumber = data.line
console.log(filePath) //C:\Apache24\htdocs\select2-bootstrap\logs\rooms\2017\05\12\p_2\p_2_12_05_2017_json.log
console.log(rowNumber) //35
nthline(rowNumber, filePath)
.then(line => console.log(line))
```

**Comment by BorisChumichev** [comment]
It didn‘t even print a `rowRumber` you passed to `console.log`...
Do you still have the problem? Try to catch and display an error if you do.
```
const nthline = require('nthline')
 , filePath = path.join(__dirname, log_dir)
 , rowNumber = data.line

nthline(rowNumber, filePath)
  .then(line => console.log(line))
  .catch(error => console.log(error))
```

**Comment by BorisChumichev** [comment]
Which node version do you use?

**Comment by fabi0w** [comment]
```
[RangeError: Requested line 49 but 'C:\Apache24\htdocs\select2-bootstrap\logs\ro
oms\2017\05\18\q_3\q_3_18_05_2017_json.log' has only 50 lines]
```

version --> Your environment has been set up for using Node.js 4.4.7 (ia32) and npm.

**Comment by fabi0w** [comment]
I ended up using fs.createReadStream ... and pass line by line .... not optimized this! ...

**Comment by BorisChumichev** [comment]
can you please provide the `C:\Apache24\htdocs\select2-bootstrap\logs\ro
oms\2017\05\18\q_3\q_3_18_05_2017_json.log` file?

**Comment by fabi0w** [comment]
@BorisChumichev  http://textuploader.com/d9huk
