### ISSUE TITLE
Rejects when given line is the last line in a file

### ISSUE THREAD

**Issue by Torniojaws** [BorisChumichev/node-nthline#2]
If you have a file with contents:
```
hello\n
there\n
```
And you call `nthline(2, '/tmp/testfile', ...)`, you will get this interesting error:
```
UnhandledPromiseRejectionWarning: RangeError: Requested line 2 but '/tmp/testfile' has only 2 lines
```

**Comment by BorisChumichev** [comment]
Thanks for pointing this out. Line indexing is zero-based. I made it more obvious by fixing README and error message in https://github.com/BorisChumichev/node-nthline/commit/11a3bd5f22149d99a513e6cf154cb2389bed0eed
